### ISSUE TITLE
Starting tutorial

### ISSUE THREAD

**Issue by RCallejo2** [Bukimedia/PrestaSharp#140]
I am experimenting problems when trying to compile my first c# application using vs .net. I add a reference to the bukimedia.prestasharp library but it seems that it does not recognise it. Surely it is a problem of expertise because I am very new on .net. Is it there any manyal about how to compile a Windows Form Application using this library?

Thanks in advance.

**Comment by citrusO2** [comment]
1. Reference to the library in the project.

2. You also need to reference to the library's namespace or use the full name of the library in the source-code where you want to use the library.

Google is your friend, there is nothing library specific, so there should be plenty of tutorials

----- Ursprüngliche Nachricht -----
Von: "RCallejo2" <notifications@github.com>
Gesendet: ‎30.‎05.‎2015 14:10
An: "Bukimedia/PrestaSharp" <PrestaSharp@noreply.github.com>
Betreff: [PrestaSharp] Starting tutorial (#140)

I am experimenting problems when trying to compile my first c# application using vs .net. I add a reference to the bukimedia.prestasharp library but it seems that it does not recognise it. Surely it is a problem of expertise because I am very new on .net. Is it there any manyal about how to compile a Windows Form Application using this library?
Thanks in advance.

**Comment by RCallejo2** [comment]
USing the full name of the library WAS the solution. Thanks a lot. I fell disappointed when loosing so much time for such a stupid issue. Microsoft, where are you!!!. 

Aupa Athletic!!!
