### ISSUE TITLE
Get Customers Updated or new

### ISSUE THREAD

**Issue by ekhidna** [Bukimedia/PrestaSharp#145]
Hello Everyone

Hello PrestaSharp community. I'm making a sync between Prestashop and an ERP. Is there a way I can get new Customers in Prestasharp since a date onwards. I know I can store the last customer id and than get all after that one. But is there any other way?.
I ask this because of my other main question: How can I get Customer that have been Updated through PrestaSharp?
Every help is welcome.
Thank you. Keep up the good work.

**Comment by RCallejo2** [comment]
I am too new to confirm it but you can use the "date_upd" field to know when a Customer has been created or updated.
However, I am actually missing a global solution for knowing when something has been updated or modifying through Prestashop web interface instead of cheking table by table. I am sure there must be a solution implemented for this...(mayby a global query could be implemented by prestashop gurus). Let´s wait for someone´s else answers.
