### ISSUE TITLE
product_feature is actually feature

### ISSUE THREAD

**Issue by MrViSiOn** [Bukimedia/PrestaSharp#213]
Hi!

I just start a project with this library, but I got some questions about product features.

I think that what you develop as product_feature is actually feature... 

Feature entity has id_feature, position, and name fields, while product_feature has id_feature ,id_product and id_product_feature...

Or How can I add a feature to a product?

Thank you

**Comment by mulflar** [comment]
Hi
Let's see. In Prestasharp you have product_feature and product_feature_value. They go to ps_feature, and to ps_feature_product and ps_feature_value in the tables.

product_feature is to define the feature, for example "ISBN", then product_feature_value is to define the value of the feature for one product.

If the feature is already created (because you created in web, or you created using product_feature) you can ask for the id using a filter by name, or just hardcode the id, and then add product_feature_value.

I hope it helps

**Comment by MrViSiOn** [comment]
Thank you so much muflflar...

This helps me out a lot, I was playing with functions and objects and I actually know how this api works.

I will keep writting and asking if I have some isuses.

Thank you!
