### ISSUE TITLE
Error updating product utf-8 support

### ISSUE THREAD

**Issue by fantonifra** [Bukimedia/PrestaSharp#341]
Hi,
 using Prestashop  after I upgrade MySql from 5.5 to 8.0.11 and Php from 5.6 to 7.0 (7.1 or 7.2) I got an error updating a product with ProductFactory.

I investigated deeply and I found this error in prestahop log:
_ERROR 	v1.7.2.4	2019/01/30 - 16:41:18: Link to database cannot be established:SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers at line 102 in file classes/db/DbPDO.php_ 

in DbPdo.php the exception is raised here:
`public function connect()
    {
        try {
            $this->link = $this->_getPDO($this->server, $this->user, $this->password, $this->database, 5);
        } catch (PDOException $e) {
            throw new PrestaShopException('Link to database cannot be established:'.$e->getMessage());
        }`

It seems this issue is related to the utf8 support; we found several post in internet about this but no one help us to fix it. We tried also to use old versione of php but without result.
Do you have a suggestion?
Thanks in advance
Francesco

**Comment by mowcixo** [comment]
It seems to be related with your server configuration, since issues are made for reporting problems with PrestaSharp library I would refer you to [PrestaShop Issues](https://github.com/PrestaShop/PrestaShop/issues)

Feel free to comment your problem in our Slack group, under the #general topic too: https://join.slack.com/t/prestasharp/shared_invite/enQtNTM2OTI1OTg0NzUyLTY4NDdkZDFmY2EwMGE4MTMzZjk5YzZiMTk3MzUwNzUxNTdhMWEwZjFjNDJiZTIyMjI0MDM0NTcwMzIzNGI0Njc
